# Generated by Django 4.1.3 on 2026-09-16 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barber', '0003_barber_bio_barber_break_end_barber_break_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('STOCK_LOW', 'Estoque Baixo'), ('SYSTEM', 'Sistema')], default='SYSTEM', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='barber.barber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
