# Generated by Django 4.1.3 on 2026-09-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_whatsappreminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsAppReminder',
        ),
    ]
