# Generated by Django 5.1.4 on 2024-12-12 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='services.services'),
            preserve_default=False,
        ),
    ]
