# Generated by Django 4.1.3 on 2026-09-16 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_barberclientnote'),
        ('services', '0002_services_barber'),
        ('schedule', '0003_schedule_status_alter_schedule_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='client_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='client.client'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='services.services'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('bloqueado', 'Bloqueado')], default='agendado', max_length=20),
        ),
    ]
