# Generated by Django 4.1.3 on 2026-09-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_barber_bio_barber_break_end_barber_break_start_and_more'),
        ('schedule', '0004_alter_schedule_client_name_alter_schedule_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='barber.barber')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
