# Generated by Django 4.1.3 on 2026-09-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_barberclientnote'),
        ('barber', '0003_barber_bio_barber_break_end_barber_break_start_and_more'),
        ('services', '0002_services_barber'),
        ('schedule', '0005_vacation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('notified', 'Avisado'), ('cancelled', 'Cancelado')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='barber.barber')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='client.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('client', 'barber', 'service', 'date')},
            },
        ),
    ]
