# Generated by Django 4.1.3 on 2026-07-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estoque_minimo',
            field=models.IntegerField(default=5),
        ),
    ]
