# Generated by Django 4.1.3 on 2026-09-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_estoque_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disponivel_na_loja',
            field=models.BooleanField(default=False),
        ),
    ]
