# Generated by Django 4.1.3 on 2026-09-17 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_barber_bio_barber_break_end_barber_break_start_and_more'),
        ('store', '0002_store_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_orders', to='barber.barber'),
        ),
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=12),
        ),
    ]
