# Generated by Django 4.1.3 on 2026-09-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_store_barber_store_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'Pix'), ('retirada', 'Pagar na retirada')], default='retirada', max_length=10),
        ),
    ]
