# Generated by Django 5.1.4 on 2026-03-19 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_finances_total'),
        ('schedule', '0003_schedule_status_alter_schedule_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finances',
            old_name='total',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='finances',
            name='store',
        ),
        migrations.AddField(
            model_name='finances',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='finances',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], default='entrada', max_length=10),
        ),
        migrations.AlterField(
            model_name='finances',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.schedule'),
        ),
    ]
