# Generated by Django 5.1.4 on 2026-03-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_alter_barber_email'),
        ('finance', '0003_rename_total_finances_valor_remove_finances_store_and_more'),
        ('schedule', '0003_schedule_status_alter_schedule_end_time'),
        ('store', '0002_store_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finances',
            name='descricao',
        ),
        migrations.AddField(
            model_name='finances',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barber.barber'),
        ),
        migrations.AlterField(
            model_name='finances',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule'),
        ),
    ]
