# Generated by Django 5.1.4 on 2026-09-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_remove_finances_descricao_finances_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finances',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'Pix')], max_length=20, null=True),
        ),
    ]
