# Generated by Django 4.1.3 on 2026-09-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_finances_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='finances',
            name='categoria',
            field=models.CharField(blank=True, choices=[('aluguel', 'Aluguel'), ('produtos', 'Produtos/Insumos'), ('utilidades', 'Luz/Água/Internet'), ('marketing', 'Marketing'), ('outros', 'Outros')], max_length=20, null=True),
        ),
    ]
