# Generated by Django 4.1.3 on 2026-09-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_alter_barber_email'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='barber.barber')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_notes', to='client.client')),
            ],
            options={
                'verbose_name': 'Nota do Barbeiro sobre Cliente',
                'verbose_name_plural': 'Notas dos Barbeiros sobre Clientes',
                'unique_together': {('barber', 'client')},
            },
        ),
    ]
