# Generated by Django 4.1.3 on 2026-09-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_alter_barber_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='break_end',
            field=models.TimeField(default='13:00'),
        ),
        migrations.AddField(
            model_name='barber',
            name='break_start',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AddField(
            model_name='barber',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/photos/'),
        ),
        migrations.AddField(
            model_name='barber',
            name='specialties',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='work_end',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='barber',
            name='work_start',
            field=models.TimeField(default='08:00'),
        ),
    ]
